  
version: '3.4'

services:
  device-registry:
    build: .
    volumes:
      - .:/robca_API
    ports:
      - 5000:80
    environment:
      - NODE_ENV=development
  mongo:
    image: mongo
  mail:
    image: bytemark/smtp
    restart: always