  
version: '3.7'

services:
  device-registry:
    build: .
    command: python run.py run -h 0.0.0.0
    volumes:
      - .:/robca_API
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    links:
      - mongo
  mongo:
    image: mongo
  mail:
    image: bytemark/smtp
    restart: always